spring:
  datasource:
    url:  jdbc:mysql://47.104.176.244:3306/xfanread
    driver-class-name: com.mysql.jdbc.Driver
    username: xfanread
    password: Fdxdz2017
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

foo: 7777
